sudo: false

dist: trusty

language: java

jdk:
  - oraclejdk8

env:
  - TRAVIS_NODE_VERSION=15
  - TRAVIS_NODE_VERSION=14
  - TRAVIS_NODE_VERSION=12
  - TRAVIS_NODE_VERSION=10

branches:
  only:
    - "master"

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install: "npm install"

script: "npm run lint && npm test"
